name: Fontend-CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: [self-hosted, linux, x64]

    steps:
    - uses: actions/checkout@v3
    # - name: Secret
    #   env:
    #     ENV_FILE: ${{ secrets.ENV_FILE }}
    #   # run: echo $ENV_FILE | base64 -d > .env
    #   run: |
    #     echo $ENV_FILE > env
    #     cat env | base64 -di > .env
    # - name: Build the Docker image
    #   run: docker build . --file Dockerfile --tag harbor.kafana.dev/ptin/bhfe:test || echo "docker build failed"
    # - name: Push the Docker image
    #   run: docker push harbor.kafana.dev/ptin/bhfe:test
    - name: Executing Deploy
      run:  |
        free -m
        bash /webapps/brotherhood/frontend/deploy.sh

    # - name: Executing remote ssh command
    #   uses: appleboy/ssh-action@master
    #   with:
    #     host: ${{ secrets.SSH_HOST }}
    #     username: ${{ secrets.SSH_USER }}
    #     key: ${{ secrets.SSH_KEY }}
    #     script: |
    #                 free -m
    #                 bash /webapps/brotherhood/frontend/deploy.sh